wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1672171608
    t:
      1:
      - 1
      - 3
      - 5
      - 9
      - 11
      2:
      - 1
      - 3
      - 5
      - 9
      - 11
      4: 3.9.7
      5: 0.12.1
      6: 4.24.0
      8:
      - 1
      - 4
      - 5
